[package]
name = "solmon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.1.2"
clap = "2.33.1"
log = "0.4.17"
miette = "5.5.0"
tokio = "1.24.1"
watchexec = "2.1.0"
